### ISSUE TITLE
Quote posts don't open in a new page

### ISSUE THREAD

**Issue by rehmansaad** [jxnblk/Ashley#24]
For example check my blog thisrambler.tumblr.com and take a look at the last post. 

Now if I go into the dashboard, I can indeed access the quote in it's new window:

http://thisrambler.tumblr.com/post/55632414079/yet-another-test-how-do-i-open-the-post-in-a-new

The link in the dashboard is the top right corner, when you over it, it turns into a folded page style thing. It would be really great if clicking on the quote or somewhere else opened it in new window.

And you already know this, you have a Great theme! Just Love it. Great work, please keep it up :)

**Comment by jxnblk** [comment]
You should be able to click the date on any post to get to the permalink page. Is that what you're referring to?

**Comment by rehmansaad** [comment]
Thank you! This totally works. Silly me!
