### ISSUE TITLE
disqus comments

### ISSUE THREAD

**Issue by ghost** [jxnblk/Ashley#25]
Please add disqus comments setting to tumblr theme.

**Comment by jxnblk** [comment]
Sorry, I won't be adding Disqus to this theme.

**Comment by irosenb** [comment]
+1

**Comment by phalgun** [comment]
@iMihael @irosenb I have a fork with Disqus integrated - https://github.com/jxnblk/Ashley/pull/29 
Feel free to use if needed. 

@jxnblk I respect your decision to not allow Disqus to your theme. I hope you don't mind others using the fork which lets them. Let me know if you want me to bring it down.

**Comment by jxnblk** [comment]
@phalgun of course I don't mind. That's what forking is for :)
