### ISSUE TITLE
Disqus integration

### ISSUE THREAD

**Issue by flegontovna** [jxnblk/Ashley#28]
Just a suggestion because I am no expert. I think integrating Disqus comments would be a great plus. http://disqus.com/
Thanks for listening!

**Comment by maique** [comment]
+1 for disqus integration.

**Comment by phalgun** [comment]
+1 for disqus integration. 
Or would you welcome a pull request?

**Comment by phalgun** [comment]
@jxnblk Submitted a pull request for Disqus integration, https://github.com/jxnblk/Ashley/pull/29

cc/ @flegontovna @maique could you test the PR please?

**Comment by MasterGroosha** [comment]
+1 It would be great to add Disqus
